version: '2'
networks:
  skywalking-net:
    driver: bridge
services:
  elasticsearch:
    restart: always
    image: wutang/elasticsearch-shanghai-zone
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - skywalking-net
  
  skywalking:
    restart: always
    image: wutang/skywalking-docker:latest
    container_name: skywalking
    environment:
      - ES_CLUSTER_NAME=elasticsearch
      - ES_ADDRESSES=elasticsearch:9300
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 8080:8080
      - 10800:10800
      - 11800:11800
      - 12800:12800
    networks:
      - skywalking-net
